### ISSUE TITLE
Is ASP.NET Core Identity a requirement?

### ISSUE THREAD

**Issue by carlospence** [brunohbrito/JPProject.IdentityServer4.AdminUI#110]
Is it possible to decouple User management form IS4 Admin UI. Would love to use it on an existing project that has its own user management but just want to use your project for IdentityServer Admin management only such as Client, APi, Identity, Resources, Persistent Grants etc

**Comment by brunohbrito** [comment]
Hi @carlospence ,

Yes, it's possible to decouple them. At first versions just the Management was available.

User Management uses the `UserControler`  and `ManagementController` from **Jp.Management**.
I'll list where you need to pay attention to accomplish that:

* UserControler
* ManagementController
* IUserManagerAppService
* IUserAppService
* IUserService
* IImageStorage

Everything at `Jp.Infra.CrossCutting.Identity` is related with ASP.NET Identity Core.

At first glance, I could say you need to change:

_Removing Identity configuration_  (Startup.cs)
```
// Identity Database
services.AddAuthentication(Configuration);
```

Update IDS4 config with your own server (Startup.cs):
```
 // configure auth Server
services.AddIdentityServerAuthentication(_logger, Configuration);
```

For Angular App
Update the `environment.ts` from Angular App (Admin-UI) to use your SSO.
