### ISSUE TITLE
.net core v3

### ISSUE THREAD

**Issue by brunohbrito** [brunohbrito/JPProject.IdentityServer4.AdminUI#137]
Upgrade to ASP.NET Core 3

**Comment by brunohbrito** [comment]
Current: 
Awaiting some components that still in preview:
- Pomelo MySql EF
- Swashbuckle Swagger
- npgsql bug

Some bugs at Api

**Comment by EatonEvents** [comment]
Swashbuckle still in the Release Candidate state and still lot more to go with dependencies.
