### ISSUE TITLE
Api Resource List not renderining

### ISSUE THREAD

**Issue by niteshgaba** [brunohbrito/JPProject.IdentityServer4.AdminUI#19]
Hi, 

I was trying the admin ui. I could see the response from the api-resource/list i.e, "{"Success":true,"Data":[{"Name":"xxx","Description":"OAuth2 Server Management Api"}],"Errors":null}"

But the same is not rendering on the html page. The page is showing loader whereas the call to get the data has finished. Any idea?

**Comment by brunohbrito** [comment]
Hi,

I'll check it today

**Comment by brunohbrito** [comment]
@niteshgaba 

I realized that after few minutes the access_token expires. Then Admin-Ui wasn't renewing it. So I've made some changes and I believe it won't occur at next version.

**Comment by brunohbrito** [comment]
@niteshgaba Check it again! I've increased expiration time and changed the openid connect config at Admin-ui

I'm closing it, feel free to open again if the problem still happen!
