### ISSUE TITLE
Aurora Mysql - Migration Problem

### ISSUE THREAD

**Issue by eflorespalma** [brunohbrito/JPProject.IdentityServer4.AdminUI#23]
Hi , first at all thanks for the project.

I run the demo in mysql on my local machine and Azure for mysql too and everything was ok, but when i try to run it  in an RDS instance (Aurora Mysql), I had some problems with the migrations, the tables were created correctly, the problems were with the data migration, i got an exception:

Value cannot be null.
Parameter name: key

```
if (!context.Clients.Any())
                {
                    foreach (var client in Clients.GetAdminClient(configuration).ToList())
                    {
//The problem is here when it tries to insert the client data
                        await context.Clients.AddAsync(client.ToEntity());
                    }

                    await context.SaveChangesAsync();
                }

                if (!context.IdentityResources.Any())
                {
                    var identityResources = ClientResources.GetIdentityResources().ToList();

                    foreach (var resource in identityResources)
                    {
                        await context.IdentityResources.AddAsync(resource.ToEntity());
                    }

                    await context.SaveChangesAsync();
                }

                if (!context.ApiResources.Any())
                {
                    foreach (var resource in ClientResources.GetApiResources().ToList())
                    {
                        await context.ApiResources.AddAsync(resource.ToEntity());
                    }

                    await context.SaveChangesAsync();
                }
```

**Comment by brunohbrito** [comment]
Hi @eflorespalma,

The migration files was auto generated with Pomelo Mysql driver. Maybe, if you change it. Then it could generate a different one at Aurora.

Try to remove the Migrations, then add it again:
1. Remove all files from `src\Backend\Jp.Infra.Migrations.MySql\Migrations`
2. Remove Nuget package Pomelo.EntityFrameworkCore.MySql
3. Add package MySql.Data.EntityFrameworkCore
4. Then open a cmd and navigate to `src\Backend\Jp.Infra.Migrations.MySql`

Run these commands:
* dotnet ef migrations add Initial -c EventStoreContext -o Migrations/EventStore --startup-project ..\..\Frontend\Jp.UI.SSO\Jp.UI.SSO.csproj
* dotnet ef migrations add Initial -c ApplicationIdentityContext -o Migrations/Identity --startup-project ..\..\Frontend\Jp.UI.SSO\Jp.UI.SSO.csproj
* dotnet ef migrations add Initial -c JpContext -o Migrations/IdentityServer --startup-project ..\..\Frontend\Jp.UI.SSO\Jp.UI.SSO.csproj

I hope it will work. If don't let me know, then I'll try to test directly from Aurora.

**Comment by eflorespalma** [comment]
Hello @brunohbrito thanks for the answer, I will try it and then I will tell you how it was.
