### ISSUE TITLE
Translation 🇩🇪 

### ISSUE THREAD

**Issue by thisIsTheFoxe** [brunohbrito/JPProject.IdentityServer4.AdminUI#235]
**Is your feature request related to a problem? Please describe.**
We are a german company who think about using this project.. would be great to have a german translation for the frontend :)

**Describe the solution you'd like**
Just an extra de.json in the i18n folder ^^

**Describe alternatives you've considered**
uhm..... ok..?

**Additional context**
I'd just fork & PR if that's ok? ^^

**Comment by thisIsTheFoxe** [comment]
🇩🇪

**Comment by brunohbrito** [comment]
> I'd just fork & PR if that's ok? ^^ 

Okay! Translations are welcome!
