### ISSUE TITLE
Will JPProject or IdentityServer4 will work out of the box for PostGreSQL

### ISSUE THREAD

**Issue by TameezM** [brunohbrito/JPProject.IdentityServer4.AdminUI#239]
It just a clarification question not a bug instead.

Will JPProject or IdentityServer4 will work out of the box for PostGreSQL

For our project, we want to use PostGreSQL rather than MSSQL as it involves license cost.

**Comment by brunohbrito** [comment]
Hi @TameezM ,

Yes, we're using EF Core and Npgsql.EntityFrameworkCore.PostgreSQL driver. So it should work with any EF Core driver.
