### ISSUE TITLE
CosmosDb

### ISSUE THREAD

**Issue by ekjuanrejon** [brunohbrito/JPProject.IdentityServer4.AdminUI#26]
hello

Sounds good

How about using cosmosdb instead of mysql or sql

**Comment by brunohbrito** [comment]
Hi @ekjuanrejon 

I've never tried it. But the project use EF and it supports CosmosDB. There is two options.
1. Add CosmosDB compatibility, by instrumenting `Jp.UI.SSO.Configuration.DbSettingsConfig` and `Jp.Management.Configuration`. And generating a CosmosDB migration files.
2. Removing the options for supporting many databases and let the developers decide what they will use.

My first impression is that the first option will be better for now. It could became a problem in future. But for now it seems ok for me.

I'll track cosmosDB for next release!

**Comment by brunohbrito** [comment]
@ekjuanrejon 

Actually CosmosDB EntityFramework  is in preview mode. So I believe that is reasonable to wait for stable version of it.

https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/3.0.0-preview6.19304.10?_src=template
