### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by ekjuanrejon** [brunohbrito/JPProject.IdentityServer4.AdminUI#27]
I was unable to get it working on my local docker in windows

No Grants have been persisted

**Comment by brunohbrito** [comment]
Hi @ekjuanrejon 

The problem was in requireHttps at `oauth-config.ts`. Now seems to be ok at PR #29!

**Comment by ekjuanrejon** [comment]
Hello, I pull down the docker images and i still have the same problem

I have a scree with the Waiting while server is loading some info

**Comment by ekjuanrejon** [comment]
I mean to tell you that I pulled new images from docker and is now working
