### ISSUE TITLE
Can't update Client's Allowed Grant Types

### ISSUE THREAD

**Issue by matheusjulio96** [brunohbrito/JPProject.IdentityServer4.AdminUI#272]
When editing a Client's Allowed Grant Types, the JsonPatchDocument fails to apply because the Client's attribute AllowedGrantTypes is an ICollection and doesn't have index [0], which returns the error 'The target location specified by path segment '0' was not found.'.

**Comment by brunohbrito** [comment]
Hi @matheusjulio96 

I know this bug, I'll provide a fix asap.

**Comment by brunohbrito** [comment]
It fixed at this new version
https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI/pull/277
