### ISSUE TITLE
Light-install: No DbContext named 'ApplicationIdentityContext' was found.

### ISSUE THREAD

**Issue by ben-lierman-craxit** [brunohbrito/JPProject.IdentityServer4.AdminUI#302]
**Context**
I'm doing a light-installment of JPProject, and am setting up my database. To do so I'm following the add migration command from Configuration\AdminUiMigrationHelpers.cs

**Describe the bug**
When running the command `Add-Migration DbInit -context ApplicationIdentityContext -output Data/Migrations` in the Package Manager Console, I get following error: `No DbContext named 'ApplicationIdentityContext' was found.`

**To Reproduce**
1. Clone the [JPProject.IdentityServer4.AdminUI](https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI) repository
2. Run the command specified in src\Backend\JPProject.Admin.Api\Configuration\AdminUiMigrationHelpers.cs
3. See error

**Expected behavior**
I was expecting a migrations folder to be created containing the migrations needed to run the update-database command on in order to get my database set for running the AdminUI.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 home]

**Comment by brunohbrito** [comment]
Hi @ben-lierman-craxit,

The comment it's wrong. Sorry. I'll change it.
It should be:

Nuget package manager: Add-Migration DbInit -context EventStoreContext -output Data/Migrations
Dotnet CLI: dotnet ef migrations add DbInit -c EventStoreContext -o Data/Migrations
