### ISSUE TITLE
ERROR: Service 'jpproject-light-api' failed to build:

### ISSUE THREAD

**Issue by anuj-sharrma** [brunohbrito/JPProject.IdentityServer4.AdminUI#311]
When i execute the command docker-compose up on step 16 i got below erro:
Step 16/17 : COPY --from=publish /app/publish .
ERROR: Service 'jpproject-light-api' failed to build: COPY failed: file does not exist

Plz suggests.

**Comment by brunohbrito** [comment]
Hi @anuj-sharrma 

I just tried a clean and fresh install from this repo. It was successfull. Could you provide a full log?

**Comment by anuj-sharrma** [comment]
![ErrorProject](https://user-images.githubusercontent.com/62496874/77861090-93175d00-7230-11ea-85f6-8f0f4c98d39f.PNG)

Here is the file for your reference.

**Comment by anuj-sharrma** [comment]
@brunohbrito I am requesting you to please provides solution against my issue.
