### ISSUE TITLE
Feature - Add sdk for management API

### ISSUE THREAD

**Issue by marcrib** [brunohbrito/JPProject.IdentityServer4.AdminUI#33]
- A simple SDK for management user

**Comment by brunohbrito** [comment]
Hi @marcrib 

Can you explain what you mean with a SDK? What do you expect?

Actually to manage user the project provide an API. If you inspect this api you'll figure out that it call an Application Layer. There is exposed all management features.

Btw, let me know your ideas and let discuss about it!

**Comment by marcrib** [comment]
Hi @brunohbrito 

Similar to auth.sdk

Integrate machine to machine
