### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by johndcollins** [brunohbrito/JPProject.IdentityServer4.AdminUI#332]
I'm trying to build this project and getting an error during npm install

**To Reproduce**
1. Open the folder in VS Code
2. Run npm install

**Expected behavior**
npm install finishes successfully 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome,

**Additional context**
Error:

 info it worked if it ends with ok

1 verbose cli [

1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',

1 verbose cli   'run',

1 verbose cli   'napa'

1 verbose cli ]

2 info using npm@6.14.4

3 info using node@v12.16.2

4 verbose run-script [ 'prenapa', 'napa', 'postnapa' ]

5 info lifecycle jp-project@1.1.0~prenapa: jp-project@1.1.0

6 info lifecycle jp-project@1.1.0~napa: jp-project@1.1.0

7 verbose lifecycle jp-project@1.1.0~napa: unsafe-perm in lifecycle true

8 verbose lifecycle jp-project@1.1.0~napa: PATH: 
9 verbose lifecycle jp-project@1.1.0~napa: CWD: C:\AdminUI

10 silly lifecycle jp-project@1.1.0~napa: Args: [ '/d /s /c', 'napa' ]

11 silly lifecycle jp-project@1.1.0~napa: Returned: code: 1  signal: null

12 info lifecycle jp-project@1.1.0~napa: Failed to exec napa script

13 verbose stack Error: jp-project@1.1.0 napa: `napa`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)

13 verbose stack     at EventEmitter.emit (events.js:310:20)

13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)

13 verbose stack     at ChildProcess.emit (events.js:310:20)

13 verbose stack     at maybeClose (internal/child_process.js:1021:16)

13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

14 verbose pkgid jp-project@1.1.0

15 verbose cwd C:\AdminUI

16 verbose Windows_NT 10.0.18363

17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "napa"

18 verbose node v12.16.2

19 verbose npm  v6.14.4

20 error code ELIFECYCLE

21 error errno 1

22 error jp-project@1.1.0 napa: `napa`

22 error Exit status 1

23 error Failed at the jp-project@1.1.0 napa script.

23 error This is probably not a problem with npm. There is likely additional logging output above.

24 verbose exit [ 1, true ]

**Comment by johndcollins** [comment]
From what I can gather, the problem is the && on windows. Do you have a fix for this?

**Comment by brunohbrito** [comment]
Hi,

Actually I'm running the development from a windows environment. The container is running under linux. Both are running fine.

btw, In command you can use &&.
![image](https://user-images.githubusercontent.com/7241156/81519676-70409400-9318-11ea-89a4-1999bcb3b5fc.png)

At powershel you need to update to preview 7, since the last version doesn't support &&. The closest is ;
![image](https://user-images.githubusercontent.com/7241156/81519731-96663400-9318-11ea-9c3f-170b3510e33e.png)

**Comment by OblivionSY** [comment]
I have also just cloned the repo and have issues with npm - even running separately, or using the ; does not work:

This seems to be the error that is shown

> jp-project@1.1.0 napa C:\Projects\JPProject.IdentityServer4.AdminUI\src\Frontend\Jp.AdminUI
> napa

info git git://github.com/miloszfalinski/jquery.flot.spline into jquery.flot.spline
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'clone',
    '--depth',
    '1',
    '-q',
    'git://github.com/miloszfalinski/jquery.flot.spline',
    'C:\\Projects\\JPProject.IdentityServer4.AdminUI\\src\\Frontend\\Jp.AdminUI\\node_modules\\jquery.flot.spline'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jp-project@1.1.0 napa: `napa`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jp-project@1.1.0 napa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output 
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\syates\AppData\Roaming\npm-cache\_logs\2020-05-19T15_37_48_184Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jp-project@1.1.0 install: `npm run napa`
npm ERR! Exit status 1

**Comment by brunohbrito** [comment]
I'm working on it

**Comment by OblivionSY** [comment]
Is there a PR or branch to look at with the issue fixed?
