### ISSUE TITLE
This project is nice 

### ISSUE THREAD

**Issue by 596442958** [brunohbrito/JPProject.IdentityServer4.AdminUI#38]
i think maybe you need add localization for other languages (chinese?)

**Comment by brunohbrito** [comment]
Hi, 

It is amazing! But if I provide others languages than portuguese or english, like chinese, it'll be autogenerated by Google Translator.

I could do that, but feel free to make a PR!

**Comment by 596442958** [comment]
@brunohbrito  in china can't access google website!!!

**Comment by brunohbrito** [comment]
I'll provide Chinese language. But I don't have enough skill to check if it's right!

**Comment by brunohbrito** [comment]
There are new several translation. They were all auto generated, so plz, don't blame me if something is really weird!
