### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by niteshgaba** [brunohbrito/JPProject.IdentityServer4.AdminUI#4]
Hi,

Could you please share how can we handle onTokenReceived, OAuthSuccessEvent or any other events in this?

**Comment by brunohbrito** [comment]
You can handle events from OIDC in API at `Jp.Management/Configuration/AuthenticationConfig.cs`

```
services.AddAuthentication(...)
                .AddOpenIdConnect("oidc", options =>
                {                  
                   /**/
                    options.Events = new OpenIdConnectEvents
                    {
                       OnTokenResponseReceived = context =>
                       {

                           return Task.CompletedTask;
                       }
                    };
                });

```
Read more at [OpenIdConnectEvents Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents?view=aspnetcore-2.2)

For IdentityServer4 events there is no much what you can do. They don't provide a way to handle or intercept it's own events.

BTW, check more at [IdentityServer4 Events](http://docs.identityserver.io/en/latest/topics/events.html)
