### ISSUE TITLE
Old Scope configuration example

### ISSUE THREAD

**Issue by psmorandi** [brunohbrito/JPProject.IdentityServer4.AdminUI#404]
**Describe the bug**
Api resource configuration documentation is using an old version of IdentityServer4 as example. Now scopes are just a list of strings. I guess this the new ApiScopes configuration required:
```C#
new ApiScope("jp_api.is4", "OAuth2 Server")
```

**To Reproduce**
1. Go to 'README.md'
2. Scroll down to 'Light Install' at 'Api resource configuration'
4. See old configuration specification

**Comment by brunohbrito** [comment]
Hi, thanks!

I'll change asap
