### ISSUE TITLE
Invalid object name 'ApiClaims

### ISSUE THREAD

**Issue by omikolaj** [brunohbrito/JPProject.IdentityServer4.AdminUI#414]
**Describe the bug**
Retrieving list of Protected Resources from JP Api project front-end throws an exception "Invalid object name 'ApiClaims". Im guessing this was not updated as ApiClaims no longer exists in Identity Provider 4 schema. Was this supposed to be 'ApiResourceClaim' or `ApiScopeClaim` ?

**To Reproduce**
1. Authenticate and navigate to 'Protected Resources' in the front end admin page. Or navigate the url to /api-resource
2. Notice the error displayed in the console

**Expected behavior**
Expected to get back list of protected resources

**Comment by brunohbrito** [comment]
You are trying to run it with IdentityServer4 v4 ?

**Comment by omikolaj** [comment]
Yes of course. Latest identity server 4. I was hoping to use the light weight installation for my project to avoid the complexity of other admin UI projects, but decided to abandon the idea after seeing this error and another one with a different end point. Let me know if there is anything else I can clarify
