### ISSUE TITLE
sessionCheckEventListener wrong origin http://localhost:4300 expected https://localhost:5000 event

### ISSUE THREAD

**Issue by louiseJing** [brunohbrito/JPProject.IdentityServer4.AdminUI#469]
I Start the 'Jp.UI.SSO' and 'Jp.api.Management' and the clients http://localhost:4200,http://localhost:4300 in dev environment.
Use google chrome. When I login and get /accounts/profile or  'authorize' cann't get the user profile. and coundn't get the user context.  please find some one can give me support .
`OAuthSuccessEvent {type: "user_profile_loaded", info: null}
	1. info: null
	2. type: "user_profile_loaded"
__proto__: OAuthEvent`
thanks.

**Comment by Foxite** [comment]
Did you ever fix this?

**Comment by brunohbrito** [comment]
If you are running the entire environment try [SSO](https://github.com/brunohbrito/JPProject.IdentityServer4.SSO) instead. It's working.
