### ISSUE TITLE
Update .NET 5 core, and angular 11

### ISSUE THREAD

**Issue by weedkiller** [brunohbrito/JPProject.IdentityServer4.AdminUI#472]
Hi can you release an update to .NET 5 / 6 also the nuget packages are old.

The demo page is not working

**Comment by brunohbrito** [comment]
Hi,

IdentityServer4 now is a paid component. So I'll keep it at this version. And there a lot of changes under the hood when we change to new versions. Which demands many hours of development.

I was working in a new version, then they changed the strategy and published a new version and new licence (Apache 2).

So in my vision there is no reasons to keep working and making the ecosystem stronger!
